weixin-vue-test:
  cache:
    untracked: true
    paths:
    - node_modules/
  tags:
    - weixin-jq-tag
  script:
    - echo 'start...'

  only:
    - /^.*test$/
  after_script:
    - scp -r dist/* web@47.93.35.76:/home/web/webhive/nginx/kingold-web/dist
    - scp -r html/* web@47.93.35.76:/home/web/webhive/nginx/kingold-web
